baseURL = 'https://hugo-blog-1ij.pages.dev/'
languageCode = 'zh-CN'
title = '欢迎来到我的个人博客'
theme = 'hugo-theme-reimu'
hasCJKLanguage = true

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [ ["\\[", "\\]"], ["$$", "$$"] ]
delimiters.inline = [ ["\\(", "\\)"], ["$", "$"] ]
[markup.highlight]
guessSyntax = true
noClasses = false

