baseURL = 'https://hugo-blog-1ij.pages.dev/'
languageCode = 'zh-CN'
title = '欢迎来到我的个人博客'
theme = 'hugo-theme-reimu'
hasCJKLanguage = true

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [ ["\\[", "\\]"], ["$$", "$$"] ]
delimiters.inline = [ ["\\(", "\\)"], ["$", "$"] ]
[markup.highlight]
guessSyntax = true
noClasses = false

[outputs]
home = ["Algolia", "HTML", "RSS"]
page = ["HTML"]
section = ["HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true